version: '3'

networks:
  my_network:

services: 
  nginx:
    image: nginx:latest
    container_name: web_server
    ports: 
      - "8000:80"
    volumes: 
      - ./web_apps:/var/www/html
      - ./web_server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - my_network

  mysql:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    tty: true
    volumes: 
      - ./database:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database123
      MYSQL_ROOT_PASSWORD: database123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - my_network

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web_apps
    # working_dir for easy to use composer or artisan
    working_dir: /var/www/html
    volumes: 
      - ./web_apps:/var/www/html
    networks: 
      - my_network